#Docker
spring.application.name=${APP_NAME:gateway}
server.port=${SERVER_PORT:8087}

# Discovery & Gateway
spring.cloud.gateway.server.webflux.discovery.locator.enabled=${DISCOVERY_ENABLED:true}
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=${LOWER_CASE_SERVICE_ID:false}

# OAuth2 / Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER_URI:http://localhost:8080/realms/demo}

# Routes (via ENV)
spring.cloud.gateway.routes[0].id=${ROUTE_0_ID:payment-service}
spring.cloud.gateway.routes[0].predicates[0]=Path=${ROUTE_0_PATH:/payments/**}
spring.cloud.gateway.routes[0].uri=${ROUTE_0_URI:lb://payments}
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=InternalHeaderGatewayFilter


spring.cloud.gateway.routes[1].id=${ROUTE_1_ID:booking-service}
spring.cloud.gateway.routes[1].predicates[0]=Path=${ROUTE_1_PATH:/booking/**}
spring.cloud.gateway.routes[1].uri=${ROUTE_1_URI:lb://booking}
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].filters[1]=InternalHeaderGatewayFilter


#Notifications :
spring.cloud.gateway.routes[2].id=${ROUTE_2_ID:notification-service}
spring.cloud.gateway.routes[2].predicates[0]=Path=${ROUTE_2_PATH:/notification/**}
spring.cloud.gateway.routes[2].uri=${ROUTE_2_URI:lb://NOTIFICATION}
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[2].filters[1]=InternalHeaderGatewayFilter


#Branch
spring.cloud.gateway.routes[3].id=${ROUTE_3_ID:branch-service}
spring.cloud.gateway.routes[3].predicates[0]=Path=${ROUTE_3_PATH:/branche/**}
spring.cloud.gateway.routes[3].uri=${ROUTE_3_URI:lb://BRANCH}
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[3].filters[1]=InternalHeaderGatewayFilter



#Salma
spring.cloud.gateway.routes[4].id=${ROUTE_4_ID:vehicles-service}
spring.cloud.gateway.routes[4].predicates[0]=Path=${ROUTE_4_PATH:/vehicles/**}
spring.cloud.gateway.routes[4].uri=${ROUTE_4_URI:lb://SALMA}
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[4].filters[1]=InternalHeaderGatewayFilter


#Auth
spring.cloud.gateway.routes[5].id=${ROUTE_5_ID:auth-service}
spring.cloud.gateway.routes[5].predicates[0]=Path=${ROUTE_5_PATH:/auth/**}
spring.cloud.gateway.routes[5].uri=${ROUTE_5_URI:lb://AUTH}
spring.cloud.gateway.routes[5].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[5].filters[1]=InternalHeaderGatewayFilter

#Sboui
spring.cloud.gateway.routes[6].id=${ROUTE_6_ID:auth-service}
spring.cloud.gateway.routes[6].predicates[0]=Path=${ROUTE_6_PATH:/auth/**}
spring.cloud.gateway.routes[6].uri=${ROUTE_6_URI:lb://PRICE}
spring.cloud.gateway.routes[6].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[6].filters[1]=InternalHeaderGatewayFilter

# Global Filters
spring.cloud.gateway.default-filters[0]=TokenRelay

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
spring.cloud.discovery.enabled=${DISCOVERY_ENABLED:true}
spring.cloud.gateway.discovery.locator.enabled=${DISCOVERY_ENABLED:true}

spring.main.web-application-type=reactive
